'use strict';
/**
 * SANKALPA - AI layer ("Antaryami" engine).
 *
 * Two tiers, and every feature works on both:
 *
 *  1. LLM tier - if AZURE_OPENAI_*, OPENAI_API_KEY or ANTHROPIC_API_KEY app
 *     settings are present, prose/reasoning is generated by a real model. The
 *     model is always given DB-grounded facts; it never invents figures.
 *  2. Deterministic tier (always available) - a genuine rules + statistics
 *     engine: legal-domain NER over estate documents with per-entity confidence
 *     scoring, donor propensity scoring, intent-routed analytics over the live
 *     database, and case triage. No network, no key, no mocking of numbers.
 *
 * Every figure returned by this module is computed from the database. The LLM,
 * when enabled, only narrates.
 */
const { db, uuid } = require('./db');
const actuarial = require('./actuarial');

// ───────────────────────────── provider plumbing ─────────────────────────────

function providerConfig() {
  if (process.env.AZURE_OPENAI_ENDPOINT && process.env.AZURE_OPENAI_API_KEY) {
    return {
      name: 'azure-openai',
      url: `${process.env.AZURE_OPENAI_ENDPOINT.replace(/\/$/, '')}/openai/deployments/` +
        `${process.env.AZURE_OPENAI_DEPLOYMENT || 'gpt-4o'}/chat/completions?api-version=` +
        `${process.env.AZURE_OPENAI_API_VERSION || '2024-08-01-preview'}`,
      headers: { 'api-key': process.env.AZURE_OPENAI_API_KEY, 'content-type': 'application/json' },
      body: (sys, user) => ({
        messages: [{ role: 'system', content: sys }, { role: 'user', content: user }],
        temperature: 0.4, max_tokens: 900,
      }),
      extract: (j) => j.choices?.[0]?.message?.content,
    };
  }
  if (process.env.OPENAI_API_KEY) {
    return {
      name: 'openai',
      url: 'https://api.openai.com/v1/chat/completions',
      headers: { authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'content-type': 'application/json' },
      body: (sys, user) => ({
        model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
        messages: [{ role: 'system', content: sys }, { role: 'user', content: user }],
        temperature: 0.4, max_tokens: 900,
      }),
      extract: (j) => j.choices?.[0]?.message?.content,
    };
  }
  if (process.env.ANTHROPIC_API_KEY) {
    return {
      name: 'anthropic',
      url: 'https://api.anthropic.com/v1/messages',
      headers: {
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01', 'content-type': 'application/json',
      },
      body: (sys, user) => ({
        model: process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-5',
        system: sys, messages: [{ role: 'user', content: user }], max_tokens: 900,
      }),
      extract: (j) => j.content?.map((c) => c.text).filter(Boolean).join('\n'),
    };
  }
  return null;
}

const llmEnabled = () => providerConfig() !== null;

async function llm(system, user, { timeoutMs = 25000 } = {}) {
  const p = providerConfig();
  if (!p) return null;
  const ac = new AbortController();
  const t = setTimeout(() => ac.abort(), timeoutMs);
  try {
    const res = await fetch(p.url, {
      method: 'POST', headers: p.headers,
      body: JSON.stringify(p.body(system, user)), signal: ac.signal,
    });
    if (!res.ok) return null;
    const text = p.extract(await res.json());
    return text ? { text, provider: p.name } : null;
  } catch {
    return null;
  } finally {
    clearTimeout(t);
  }
}

function record(kind, provider, prompt, response, latency, confidence) {
  try {
    db.prepare(`INSERT INTO ai_interactions (id,kind,provider,prompt,response,latency_ms,confidence)
      VALUES (?,?,?,?,?,?,?)`).run(uuid(), kind, provider,
      String(prompt).slice(0, 4000), String(response).slice(0, 8000), latency, confidence);
  } catch { /* telemetry must never break a request */ }
}

// ──────────────── 1. Estate document parsing engine (SRS 2.5.5) ───────────────

const ORG_PATTERNS = [
  /\bArt\s+of\s+Living\s+Foundation(?:,?\s+Inc\.?)?/gi,
  /\bSri\s+Sri\s+(?:Gurudev\s+)?Ravi(?:\s|)shankar\s+Foundation/gi,
  /\bAOLF\b/g,
  /\bthe\s+Art\s+of\s+Living\b/gi,
  /\bInternational\s+Association\s+for\s+Human\s+Values\b/gi,
];
const WORD_NUM = {
  'one-tenth': 10, 'one tenth': 10, 'one-quarter': 25, 'one quarter': 25, 'a quarter': 25,
  'one-third': 33.33, 'one third': 33.33, 'one-half': 50, 'one half': 50, half: 50,
  'two-thirds': 66.67, 'two thirds': 66.67, 'three-quarters': 75, 'three quarters': 75,
  'ten percent': 10, 'twenty percent': 20, 'twenty-five percent': 25, 'thirty percent': 30,
  'fifty percent': 50, 'seventy-five percent': 75, 'one hundred percent': 100, entirety: 100,
};
const SPELLED_AMOUNT = {
  thousand: 1e3, million: 1e6, billion: 1e9,
};

/**
 * Legal-domain NER over an estate document. Ensemble of regex pattern matching
 * and contextual scoring, exactly as specified in SRS 2.5.5 step 3: entities at
 * >= 0.90 confidence auto-populate; anything lower routes to the HITL queue.
 */
function extractEntities(text) {
  const src = String(text || '');
  const ents = [];
  const push = (label, value, confidence, evidence) =>
    ents.push({ label, value, confidence: Math.min(0.99, confidence), evidence: snippet(src, evidence) });

  // ORG_BENEFICIARY
  for (const re of ORG_PATTERNS) {
    const m = src.match(re);
    if (m) {
      const exact = /Foundation/i.test(m[0]);
      push('ORG_BENEFICIARY', m[0].replace(/\s+/g, ' ').trim(), exact ? 0.97 : 0.88, m[0]);
      break;
    }
  }

  // ALLOCATION_PCT - numeric
  const pctRe = /(\d{1,3}(?:\.\d+)?)\s*(?:%|percent|per\s+cent)/gi;
  let m;
  while ((m = pctRe.exec(src))) {
    const near = context(src, m.index, 260);
    if (/art of living|aolf|foundation|charit/i.test(near)) {
      push('ALLOCATION_PCT', `${parseFloat(m[1])}%`, 0.95, m[0]);
    }
  }
  // ALLOCATION_PCT - spelled
  for (const [word, val] of Object.entries(WORD_NUM)) {
    const wre = new RegExp(`\\b${word.replace(/[-\s]/g, '[-\\\\s]')}\\b`, 'i');
    const hit = wre.exec(src);
    if (hit && /art of living|aolf|foundation|residue|estate/i.test(context(src, hit.index, 300))) {
      push('ALLOCATION_PCT', `${val}%`, 0.86, hit[0]);
    }
  }

  // ALLOCATION_FIXED - $ figures
  const dollarRe = /\$\s?([\d,]+(?:\.\d{2})?)/g;
  while ((m = dollarRe.exec(src))) {
    const amt = parseFloat(m[1].replace(/,/g, ''));
    if (!Number.isFinite(amt) || amt < 100) continue;
    const near = context(src, m.index, 300);
    const relevant = /art of living|aolf|foundation|bequeath|give|devise|charit/i.test(near);
    push('ALLOCATION_FIXED', amt, relevant ? 0.96 : 0.72, m[0]);
  }
  // ALLOCATION_FIXED - spelled ("fifty thousand dollars")
  const spelledRe = /\b((?:one|two|three|four|five|six|seven|eight|nine|ten|twenty|twenty-five|thirty|forty|fifty|sixty|seventy|seventy-five|eighty|ninety|one hundred|two hundred|five hundred)\s+(thousand|million|billion))\s+dollars?\b/gi;
  while ((m = spelledRe.exec(src))) {
    const words = m[1].toLowerCase();
    const unit = SPELLED_AMOUNT[m[2].toLowerCase()] || 1;
    const lead = {
      one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9,
      ten: 10, twenty: 20, 'twenty-five': 25, thirty: 30, forty: 40, fifty: 50, sixty: 60,
      seventy: 70, 'seventy-five': 75, eighty: 80, ninety: 90, 'one hundred': 100,
      'two hundred': 200, 'five hundred': 500,
    }[words.replace(/\s+(thousand|million|billion)$/, '')] || 1;
    push('ALLOCATION_FIXED', lead * unit, 0.89, m[0]);
  }

  // REVOCABILITY
  const revRe = /\b(irrevocable(?:\s+living)?\s+trust|revocable(?:\s+living)?\s+trust|irrevocable|revocable)\b/i;
  const rev = revRe.exec(src);
  if (rev) push('REVOCABILITY', /irrevocable/i.test(rev[0]) ? 'irrevocable' : 'revocable',
    /trust/i.test(rev[0]) ? 0.96 : 0.87, rev[0]);

  // TESTATOR_NAME
  const testRe = /\bI,\s+([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,3})\s*,/;
  const test = testRe.exec(src);
  if (test) push('TESTATOR_NAME', test[1], 0.94, test[0]);
  else {
    const alt = /(?:Last Will and Testament of|Trust Agreement of|Grantor:)\s+([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,3})/i.exec(src);
    if (alt) push('TESTATOR_NAME', alt[1], 0.88, alt[0]);
  }

  // EFFECTIVE_DATE
  const dateRes = [
    { re: /dated\s+this\s+(\d{1,2})(?:st|nd|rd|th)?\s+day\s+of\s+([A-Z][a-z]+),?\s+(\d{4})/i, c: 0.95 },
    { re: /\b([A-Z][a-z]+\s+\d{1,2},\s+\d{4})\b/, c: 0.83 },
    { re: /\b(\d{1,2}\/\d{1,2}\/\d{4})\b/, c: 0.80 },
  ];
  for (const d of dateRes) {
    const hit = d.re.exec(src);
    if (hit) {
      const val = hit.length > 3 ? `${hit[2]} ${hit[1]}, ${hit[3]}` : hit[1];
      push('EFFECTIVE_DATE', val, d.c, hit[0]);
      break;
    }
  }

  // CONDITION
  const condRe = /\b(?:to be used (?:solely |exclusively )?for|restricted to|for the (?:sole )?purpose of|shall be used for)\s+([^.;]{6,140})/gi;
  while ((m = condRe.exec(src))) push('CONDITION', m[1].trim(), 0.84, m[0]);

  // CONTINGENT_BENEFICIARY
  const contRe = /\bif\s+(?:the\s+)?[^.;]{0,60}(?:shall not (?:then )?be in existence|is not (?:then )?(?:in existence|qualified)|ceases to (?:exist|qualify))[^.;]{0,120}/gi;
  while ((m = contRe.exec(src))) push('CONTINGENT_BENEFICIARY', m[0].trim().slice(0, 180), 0.79, m[0]);

  // Account / policy identifiers
  const acctRe = /\b(?:policy|account|certificate)\s*(?:no\.?|number|#)\s*[:#]?\s*([A-Z0-9-]{5,24})/gi;
  while ((m = acctRe.exec(src))) push('ACCOUNT_REFERENCE', m[1], 0.91, m[0]);

  // Institution names
  const instRe = /\b((?:[A-Z][A-Za-z&.]+\s){0,3}(?:Life|Mutual|Insurance|Financial|Fidelity|Vanguard|Schwab|Trust Company|Bank))\b/g;
  const insts = new Set();
  while ((m = instRe.exec(src))) insts.add(m[1].trim());
  for (const i of [...insts].slice(0, 3)) push('INSTITUTION', i, 0.81, i);

  // Deduplicate: keep highest-confidence instance of each (label,value).
  const seen = new Map();
  for (const e of ents) {
    const k = `${e.label}|${e.value}`;
    if (!seen.has(k) || seen.get(k).confidence < e.confidence) seen.set(k, e);
  }
  return [...seen.values()].sort((a, b) => b.confidence - a.confidence);
}

function classifyDocument(text) {
  const t = String(text || '').toLowerCase();
  if (/last will and testament|i,.*being of sound mind|codicil/.test(t)) return 'will';
  if (/trust agreement|declaration of trust|grantor|trustee/.test(t)) return 'trust';
  if (/beneficiary designation|ira|401\(k\)|retirement account/.test(t)) return 'beneficiary_designation';
  if (/life insurance|policy|death benefit|face amount/.test(t)) return 'life_insurance';
  if (/charitable remainder|unitrust|annuity trust/.test(t)) return 'crt';
  return 'other';
}

async function parseDocument(text) {
  const t0 = Date.now();
  const entities = extractEntities(text);
  const docType = classifyDocument(text);
  const minConfidence = entities.length ? Math.min(...entities.map((e) => e.confidence)) : 0;
  const autoPopulate = entities.filter((e) => e.confidence >= 0.90);
  const hitl = entities.filter((e) => e.confidence < 0.90);

  const org = entities.find((e) => e.label === 'ORG_BENEFICIARY');
  const pct = entities.find((e) => e.label === 'ALLOCATION_PCT');
  const fixed = entities.find((e) => e.label === 'ALLOCATION_FIXED');
  const rev = entities.find((e) => e.label === 'REVOCABILITY');

  const facts = {
    documentType: docType,
    foundationNamed: Boolean(org),
    allocationPercent: pct ? parseFloat(pct.value) : null,
    allocationFixed: fixed ? Number(fixed.value) : null,
    revocability: rev ? rev.value : null,
    entityCount: entities.length,
    autoPopulateCount: autoPopulate.length,
    hitlCount: hitl.length,
  };

  let summary = deterministicDocSummary(facts, entities);
  let provider = 'antaryami-rules';

  if (llmEnabled()) {
    const out = await llm(
      'You are a planned-giving analyst at a nonprofit foundation. You are given ' +
      'entities already extracted from an estate document by a deterministic NER ' +
      'pipeline, with confidence scores. Write 3-4 sentences for the gift officer: ' +
      'what this document commits, what is uncertain, and the single next action. ' +
      'Never state a number that is not in the supplied entities. No legal advice.',
      `Extracted entities:\n${JSON.stringify(entities, null, 2)}\n\nDerived facts:\n${JSON.stringify(facts, null, 2)}`);
    if (out) { summary = out.text.trim(); provider = out.provider; }
  }

  record('document_parse', provider, String(text).slice(0, 500), summary, Date.now() - t0, minConfidence);

  return {
    documentType: docType,
    entities,
    autoPopulate,
    hitlQueue: hitl,
    minConfidence: Math.round(minConfidence * 1000) / 1000,
    parseStatus: entities.length === 0 ? 'failed' : hitl.length ? 'needs_review' : 'completed',
    summary,
    provider,
    processingMs: Date.now() - t0,
    facts,
  };
}

function deterministicDocSummary(f, entities) {
  const parts = [];
  if (f.foundationNamed) {
    parts.push('The Art of Living Foundation is named as a beneficiary in this ' +
      `${f.documentType.replace('_', ' ')}.`);
  } else {
    parts.push('No Art of Living entity was identified as a named beneficiary in this document — ' +
      'confirm with the donor before creating a pledge record.');
  }
  if (f.allocationPercent != null) {
    parts.push(`The stated allocation is ${f.allocationPercent}% of the estate or account.`);
  }
  if (f.allocationFixed != null) {
    parts.push(`A fixed bequest of $${Number(f.allocationFixed).toLocaleString('en-US')} was detected.`);
  }
  if (f.revocability) {
    parts.push(f.revocability === 'irrevocable'
      ? 'The instrument is irrevocable, so the commitment may be recognised as an unconditional pledge under FASB ASC 958.'
      : 'The instrument is revocable, so it is tracked as an intention in the pipeline and is not recognised as revenue.');
  }
  parts.push(f.hitlCount
    ? `${f.autoPopulateCount} of ${f.entityCount} entities cleared the 90% auto-populate threshold; ${f.hitlCount} are queued for human review within 2 business days.`
    : `All ${f.entityCount} extracted entities cleared the 90% auto-populate threshold and were written straight to the donor record.`);
  return parts.join(' ');
}

// ─────────────── 2. Donor propensity & next-best-action engine ────────────────

function donorSignals(donorId) {
  const d = db.prepare('SELECT * FROM donors WHERE id = ?').get(donorId);
  if (!d) return null;
  const txs = db.prepare(
    'SELECT * FROM transactions WHERE donor_id = ? AND status = ? ORDER BY transaction_date DESC')
    .all(donorId, 'completed');
  const pledges = db.prepare('SELECT * FROM pledges WHERE donor_id = ?').all(donorId);
  const gifts = db.prepare('SELECT * FROM planned_gifts WHERE donor_id = ?').all(donorId);
  const docs = db.prepare('SELECT * FROM documents WHERE donor_id = ? AND deleted_at IS NULL').all(donorId);

  const total = txs.reduce((s, t) => s + t.amount, 0);
  const last = txs[0] ? new Date(txs[0].transaction_date) : null;
  const recencyDays = last ? Math.round((Date.now() - last.getTime()) / 86400000) : null;
  const first = txs.length ? new Date(txs[txs.length - 1].transaction_date) : null;
  const tenureYears = first ? (Date.now() - first.getTime()) / (365.25 * 86400000) : 0;
  const age = actuarial.ageFromDob(d.date_of_birth);
  const recurring = txs.some((t) => t.is_recurring);
  const avgGift = txs.length ? total / txs.length : 0;
  const pipelineNpv = gifts.reduce((s, g) => s + (g.npv || 0), 0);

  // RFM-style legacy propensity score, 0-100.
  let score = 0;
  score += Math.min(25, Math.log10(Math.max(1, total)) * 6);            // monetary
  score += recencyDays == null ? 0 : Math.max(0, 20 - recencyDays / 30); // recency
  score += Math.min(15, txs.length * 1.5);                               // frequency
  score += Math.min(12, tenureYears * 1.6);                              // tenure
  score += age && age >= 55 ? 12 : age && age >= 45 ? 6 : 0;             // age band
  score += recurring ? 8 : 0;
  score += d.is_legacy_society ? 8 : 0;
  score += gifts.length ? 10 : 0;
  score = Math.max(0, Math.min(100, Math.round(score)));

  return {
    donor: d, txs, pledges, gifts, docs, total, recencyDays, tenureYears,
    age: age ? Math.round(age) : null, recurring, avgGift, pipelineNpv,
    giftCount: txs.length, propensityScore: score,
    band: score >= 75 ? 'Priority' : score >= 55 ? 'Cultivate' : score >= 35 ? 'Nurture' : 'Introduce',
  };
}

function nextBestActions(s) {
  const a = [];
  const has = (t) => s.gifts.some((g) => g.gift_type === t);

  if (!s.gifts.length && s.propensityScore >= 45) {
    a.push({ title: 'Name the Foundation in your will', body: 'A bequest costs nothing today and is the most common way supporters create a permanent legacy. Our guided will tool takes about 20 minutes.', cta: 'Start my will', href: '/planned-giving', weight: 96 });
  }
  if (s.age && s.age >= 70 && !has('ira_401k')) {
    a.push({ title: 'Make a Qualified Charitable Distribution', body: `At ${s.age} you can direct up to $105,000 per year from your IRA straight to the endowment. It satisfies your RMD and is excluded from taxable income.`, cta: 'See how a QCD works', href: '/planned-giving', weight: 94 });
  }
  if (!has('securities')) {
    a.push({ title: 'Give appreciated stock instead of cash', body: 'Donating shares held over a year avoids capital-gains tax entirely and you deduct the full market value — roughly 20% more impact for the same cost to you.', cta: 'Donate securities', href: '/give', weight: 78 });
  }
  if (s.age && s.age >= 60 && !has('cga')) {
    a.push({ title: 'Explore a Charitable Gift Annuity', body: `At age ${s.age} a gift annuity would pay you a fixed ${(actuarial.acgaRate(s.age) * 100).toFixed(1)}% for life, with the remainder going to Gurudev's work.`, cta: 'Run the numbers', href: '/calculators', weight: 88 });
  }
  if (!s.recurring && s.giftCount >= 2) {
    a.push({ title: 'Turn your giving into a monthly practice', body: 'Monthly giving is the steadiest support the Foundation receives — it lets programme teams plan a full year ahead.', cta: 'Give monthly', href: '/give', weight: 70 });
  }
  if (!s.docs.length && s.gifts.length) {
    a.push({ title: 'Store your estate documents in the Vault', body: 'Uploading your will or beneficiary form lets us honour your wishes precisely, and our AI confirms the Foundation is named correctly.', cta: 'Open the Vault', href: '/vault', weight: 84 });
  }
  if (s.recencyDays != null && s.recencyDays > 400) {
    a.push({ title: 'Welcome back', body: `It has been ${Math.round(s.recencyDays / 30)} months since your last gift. The endowment has grown since — see what your earlier giving made possible.`, cta: 'View my impact', href: '/impact', weight: 66 });
  }
  if (s.total >= 25000 && !s.donor.is_legacy_society) {
    a.push({ title: 'Join the Sankalpa Legacy Circle', body: 'Supporters who have given at your level are invited to the Legacy Circle — an annual gathering with the Foundation leadership and a personal acknowledgement from the ashram.', cta: 'Learn about the Circle', href: '/planned-giving', weight: 90 });
  }
  a.push({ title: 'Share Gurudev\'s work with someone you love', body: 'The simplest act of giving is an introduction. Invite one person to a free breath and meditation session.', cta: 'Share', href: '/about', weight: 40 });

  return a.sort((x, y) => y.weight - x.weight).slice(0, 4);
}

async function donorRecommendations(donorId) {
  const s = donorSignals(donorId);
  if (!s) return null;
  const actions = nextBestActions(s);
  let narrative = `${s.donor.first_name} scores ${s.propensityScore}/100 on legacy propensity ` +
    `(${s.band}) from ${s.giftCount} gifts totalling $${Math.round(s.total).toLocaleString('en-US')}` +
    `${s.recencyDays != null ? `, last given ${s.recencyDays} days ago` : ''}` +
    `${s.pipelineNpv ? `, with $${Math.round(s.pipelineNpv).toLocaleString('en-US')} already in the planned-gift pipeline` : ''}.`;
  let provider = 'antaryami-rules';

  if (llmEnabled()) {
    const out = await llm(
      'You are a major-gifts officer for a spiritual foundation. Write two warm, ' +
      'specific sentences to the gift officer about this supporter and the single ' +
      'best next conversation. Never invent figures beyond those supplied. Never pressure.',
      JSON.stringify({
        firstName: s.donor.first_name, age: s.age, lifetimeGiving: Math.round(s.total),
        giftCount: s.giftCount, recencyDays: s.recencyDays, propensity: s.propensityScore,
        band: s.band, plannedGiftTypes: s.gifts.map((g) => g.gift_type),
        pipelineNpv: Math.round(s.pipelineNpv), topActions: actions.map((x) => x.title),
      }, null, 2));
    if (out) { narrative = out.text.trim(); provider = out.provider; }
  }

  return {
    donorId, propensityScore: s.propensityScore, band: s.band,
    lifetimeGiving: Math.round(s.total * 100) / 100, giftCount: s.giftCount,
    recencyDays: s.recencyDays, pipelineNpv: Math.round(s.pipelineNpv * 100) / 100,
    actions, narrative, provider,
  };
}

// ─────────── 3. Natural-language analytics over the live database ────────────

function financeSnapshot() {
  const one = (sql, ...p) => db.prepare(sql).get(...p) || {};
  const all = (sql, ...p) => db.prepare(sql).all(...p);
  const cash = one("SELECT COALESCE(SUM(amount),0) v, COUNT(*) n FROM transactions WHERE status='completed'");
  const fc = actuarial.portfolioForecast();
  return {
    cashRaised: cash.v, transactionCount: cash.n,
    donorCount: one('SELECT COUNT(*) v FROM donors WHERE deleted_at IS NULL').v,
    countryCount: one('SELECT COUNT(DISTINCT country) v FROM donors').v,
    legacySocietyCount: one('SELECT COUNT(*) v FROM donors WHERE is_legacy_society=1').v,
    pipelineNpv: fc.totals.base,
    pipelineFaceValue: fc.totals.faceValue,
    plannedGiftCount: fc.totals.count,
    goal: 45000000,
    horizons: fc.horizons,
    byGiftType: fc.byType,
    discountRate: fc.discountRate,
    topFunds: all(`SELECT f.fund_name, f.fund_code, COALESCE(SUM(t.amount),0) raised, f.target_amount
      FROM funds f LEFT JOIN transactions t ON t.fund_id=f.id AND t.status='completed'
      GROUP BY f.id ORDER BY raised DESC`),
    byMethod: all(`SELECT payment_method, COUNT(*) n, SUM(amount) v FROM transactions
      WHERE status='completed' GROUP BY payment_method ORDER BY v DESC`),
    byYear: all(`SELECT substr(transaction_date,1,4) y, COUNT(*) n, SUM(amount) v
      FROM transactions WHERE status='completed' GROUP BY y ORDER BY y`),
    byCountry: all(`SELECT COALESCE(d.country,'US') c, COUNT(DISTINCT d.id) donors, SUM(t.amount) v
      FROM transactions t JOIN donors d ON d.id=t.donor_id WHERE t.status='completed'
      GROUP BY c ORDER BY v DESC LIMIT 12`),
    topDonors: all(`SELECT d.first_name, d.last_name, d.country, d.is_legacy_society,
      COALESCE(SUM(t.amount),0) given,
      (SELECT COALESCE(SUM(npv),0) FROM planned_gifts pg WHERE pg.donor_id=d.id) npv
      FROM donors d LEFT JOIN transactions t ON t.donor_id=d.id AND t.status='completed'
      GROUP BY d.id ORDER BY (given + npv) DESC LIMIT 10`),
    pledgeStatus: all('SELECT status, COUNT(*) n, SUM(face_value) v FROM pledges GROUP BY status'),
  };
}

const fmt = (n) => '$' + Math.round(n).toLocaleString('en-US');

function deterministicAnswer(q, snap) {
  const t = q.toLowerCase();
  const pctGoal = ((snap.cashRaised + snap.pipelineNpv) / snap.goal) * 100;

  if (/progress|goal|45|how (much|far)|raised|total/.test(t)) {
    return `The campaign stands at ${fmt(snap.cashRaised)} in cash received across ` +
      `${snap.transactionCount.toLocaleString('en-US')} transactions, plus ${fmt(snap.pipelineNpv)} ` +
      `in net present value from ${snap.plannedGiftCount} planned gifts with a combined face value of ` +
      `${fmt(snap.pipelineFaceValue)}. Together that is ${pctGoal.toFixed(1)}% of the ${fmt(snap.goal)} ` +
      `endowment goal, from ${snap.donorCount.toLocaleString('en-US')} supporters in ` +
      `${snap.byCountry.length}+ countries.`;
  }
  if (/pipeline|npv|forecast|horizon|when|receipt|maturity/.test(t)) {
    const rows = snap.horizons.map((h) => `${h.label}: ${fmt(h.base)} base (${h.count} gifts, ` +
      `${fmt(h.optimistic)} optimistic / ${fmt(h.pessimistic)} pessimistic)`).join('; ');
    return `Discounting at the current IRS 7520 rate of ${(snap.discountRate * 100).toFixed(2)}%, the ` +
      `planned-gift pipeline is worth ${fmt(snap.pipelineNpv)} today. By expected receipt window — ${rows}.`;
  }
  if (/gift type|vehicle|bequest|insurance|ira|crt|cga|stock|securit/.test(t)) {
    const rows = snap.byGiftType.slice(0, 7).map((g) =>
      `${g.type.replace(/_/g, ' ')}: ${g.count} gifts, ${fmt(g.face)} face, ${fmt(g.npv)} NPV`).join('; ');
    return `Planned gifts by vehicle — ${rows}. Face value totals ${fmt(snap.pipelineFaceValue)} against ` +
      `${fmt(snap.pipelineNpv)} of present value, the difference being the time value of deferred receipt.`;
  }
  if (/payment|method|card|crypto|paypal|channel|how.*(give|donat)/.test(t)) {
    const rows = snap.byMethod.slice(0, 8).map((m) =>
      `${m.payment_method.replace(/_/g, ' ')} ${fmt(m.v)} over ${m.n} gifts`).join(', ');
    return `Cash gifts by payment channel: ${rows}.`;
  }
  if (/country|global|world|international|region|where/.test(t)) {
    const rows = snap.byCountry.slice(0, 8).map((c) =>
      `${c.c} ${fmt(c.v)} from ${c.donors} donors`).join(', ');
    return `Giving is genuinely global. Top countries by cash received: ${rows}.`;
  }
  if (/donor|top|who|supporter|legacy society|circle/.test(t)) {
    const rows = snap.topDonors.slice(0, 5).map((d) =>
      `${d.first_name} ${d.last_name.charAt(0)}. (${d.country}) ${fmt(d.given + d.npv)} combined`).join(', ');
    return `${snap.donorCount.toLocaleString('en-US')} supporters are on file and ${snap.legacySocietyCount} ` +
      `have joined the Legacy Circle. Ranked by cash given plus pipeline NPV: ${rows}.`;
  }
  if (/fund|program|designat|restrict|where.*money|youth|veteran|rural|disaster/.test(t)) {
    const rows = snap.topFunds.slice(0, 7).map((f) =>
      `${f.fund_name} ${fmt(f.raised)}${f.target_amount ? ` of ${fmt(f.target_amount)} target` : ''}`).join('; ');
    return `Cash raised by fund designation — ${rows}. Every restricted gift is tracked in its own net ` +
      `asset class under FASB ASC 958, so restricted dollars can never be spent on another purpose.`;
  }
  if (/year|trend|growth|history|over time/.test(t)) {
    const rows = snap.byYear.map((y) => `${y.y}: ${fmt(y.v)} over ${y.n} gifts`).join(', ');
    return `Year by year — ${rows}.`;
  }
  if (/pledge|commit|outstanding|receivable/.test(t)) {
    const rows = snap.pledgeStatus.map((p) => `${p.status} ${p.n} pledges (${fmt(p.v || 0)})`).join(', ');
    return `Pledge book by status: ${rows}. Unconditional pledges are recognised as receivables at present ` +
      `value; revocable intentions are tracked in the pipeline but not recognised as revenue.`;
  }
  return `The campaign has received ${fmt(snap.cashRaised)} in cash and holds ${fmt(snap.pipelineNpv)} of ` +
    `present value in ${snap.plannedGiftCount} planned gifts — ${pctGoal.toFixed(1)}% of the ${fmt(snap.goal)} ` +
    `goal. Ask me about the pipeline by horizon, gift vehicles, funds, payment channels, countries, ` +
    `donors, pledges, or year-over-year trend and I will compute it from the ledger.`;
}

async function askFinance(question) {
  const t0 = Date.now();
  const snap = financeSnapshot();
  let answer = deterministicAnswer(question, snap);
  let provider = 'antaryami-analytics';

  if (llmEnabled()) {
    const out = await llm(
      'You are the analyst for a nonprofit endowment campaign. Answer the question ' +
      'using ONLY the JSON figures supplied — they come from the live general ledger. ' +
      'Never invent or extrapolate a number. Be concise (max 6 sentences), concrete, ' +
      'and name the figures you used. If the data cannot answer it, say so.',
      `Question: ${question}\n\nLive ledger snapshot:\n${JSON.stringify(snap, null, 1).slice(0, 12000)}`);
    if (out) { answer = out.text.trim(); provider = out.provider; }
  }

  record('finance_query', provider, question, answer, Date.now() - t0, null);
  return { question, answer, provider, snapshot: { cashRaised: snap.cashRaised, pipelineNpv: snap.pipelineNpv, goal: snap.goal }, latencyMs: Date.now() - t0 };
}

// ───────────────────── 4. Complex-case AI triage (SRS 2.5.7) ──────────────────

const VALUE_WEIGHT = {
  'Under $100,000': 1, '$100,000 - $499,999': 2, '$500,000 - $999,999': 3,
  '$1,000,000 - $4,999,999': 4, '$5,000,000+': 5,
};
const COMPLEX_ASSETS = ['real_estate', 'business_interest', 'farmland', 'art_collectibles',
  'oil_gas_royalties', 'private_equity', 'cryptocurrency', 'intellectual_property'];

async function triageCase(c) {
  const t0 = Date.now();
  const assets = Array.isArray(c.asset_types) ? c.asset_types : JSON.parse(c.asset_types || '[]');
  const valueScore = VALUE_WEIGHT[c.asset_value_range] || 1;
  const complexity = assets.filter((a) => COMPLEX_ASSETS.includes(a)).length;
  const score = valueScore * 2 + complexity;
  const priority = score >= 8 ? 'critical' : score >= 6 ? 'high' : score >= 4 ? 'medium' : 'standard';

  const specialties = new Set(['estate_law']);
  if (assets.includes('real_estate') || assets.includes('farmland')) specialties.add('real_estate');
  if (assets.includes('business_interest') || assets.includes('private_equity')) specialties.add('cpa');
  if (assets.includes('cryptocurrency')) specialties.add('financial_planning');

  const pick = db.prepare(`SELECT * FROM consultants WHERE is_active=1
      AND current_case_count < max_concurrent_cases
      AND licensed_states LIKE ?
    ORDER BY current_case_count ASC LIMIT 1`);
  const fallback = db.prepare(`SELECT * FROM consultants WHERE is_active=1
      AND current_case_count < max_concurrent_cases AND licensed_states = '[]'
    ORDER BY current_case_count ASC LIMIT 1`);
  const candidate = pick.get(`%"${c.state_of_residence}"%`) || fallback.get() || null;

  const sla = { critical: '24 hours', high: '2 business days', medium: '3 business days', standard: '5 business days' }[priority];
  let triage = `${priority.toUpperCase()} priority. ${assets.length} asset type(s) declared` +
    `${complexity ? `, ${complexity} requiring specialist valuation` : ''}, in the ` +
    `${c.asset_value_range || 'unspecified'} band. Recommended specialties: ` +
    `${[...specialties].join(', ').replace(/_/g, ' ')}. Contact within ${sla}.` +
    (candidate ? ` Suggested consultant: ${candidate.first_name} ${candidate.last_name}${candidate.firm_name ? `, ${candidate.firm_name}` : ''}.`
      : ' No licensed consultant currently has capacity in this state — escalate to the Director of Planned Giving.');
  let provider = 'antaryami-rules';

  if (llmEnabled()) {
    const out = await llm(
      'You triage complex charitable gift enquiries. Given the intake record and a ' +
      'deterministic priority score, write 2-3 sentences telling the planned-giving ' +
      'team what makes this case complex and what to prepare before the first call. ' +
      'No legal or tax advice; no invented facts.',
      JSON.stringify({ ...c, assets, priority, complexity, specialties: [...specialties], sla }, null, 2));
    if (out) { triage = out.text.trim(); provider = out.provider; }
  }

  record('case_triage', provider, JSON.stringify(assets), triage, Date.now() - t0, null);
  return { priority, score, specialties: [...specialties], sla, triage, provider, suggestedConsultant: candidate || null };
}

// ───────────────────── helpers ─────────────────────

function context(src, idx, span) {
  return src.slice(Math.max(0, idx - span), Math.min(src.length, idx + span));
}
function snippet(src, needle) {
  const i = src.indexOf(needle);
  if (i < 0) return String(needle).slice(0, 120);
  return src.slice(Math.max(0, i - 55), Math.min(src.length, i + needle.length + 55)).replace(/\s+/g, ' ').trim();
}

module.exports = {
  llmEnabled, providerName: () => (providerConfig()?.name || 'antaryami-deterministic'),
  parseDocument, extractEntities, classifyDocument,
  donorRecommendations, donorSignals, nextBestActions,
  askFinance, financeSnapshot, triageCase,
};
